### PR TITLE
DEEPLINK Feature [NEED ANDROID TEST] PART2

### PR DESCRIPTION
**Pull request by ue**
### What does this PR?
deeplink
### Steps to reproduce
open safari or chrome
for post
esteem://bookreview/@rachelhanson10/lifeunscripted-stmaxfpvvw
for user
esteem://u-e
### Issue number
#369

### Screenshots/Video

ezgif com-video-to-gif 1
ezgif com-video-to-gif 2

### CODE REVIEW

**Comment by feruzm** [comment]
@ue this is much needed feature, indeed... 
* posts mainly have 2 formats: 
1. `esteem://tag/@user/permlink`
2. `esteem://@user/permlink`
* profile format is ok but note that it will have extra sub formats
1. `esteem://@user` - open main profile
2. `esteem://@user/transfers` - open wallet page
* feed also has format
1. `esteem://trending` (feed, hot, active, promoted, etc.)
2. `esteem://trending/photography` (tag related feeds, so you can get feed for specific tags, e.g. photography

**Comment by ue** [comment]
feed formats doesnt work right now becouse of we have no tags support lets create a issue for that and linked each other when it available both of them can create.

**Comment by ue** [comment]
how can i handle main profile ? now profile routing already working. just can do now transfers routing

**Comment by feruzm** [comment]
>feed formats doesnt work right now becouse of we have no tags support lets create a issue for that and linked each other when it available both of them can create.

@ue yes, let's create issue for future updates, you don't have to do it in this PR because that's bigger change and takes time.

>how can i handle main profile ? now profile routing already working. just can do now transfers routing

main profile just points to profile and their Posts tab, `transfers` will also point profile page but with Wallet tab active.

**Pull request merged**
