### PR TITLE
Fixed pull left right #275 && fixed gif && fixed long tag 

### LINKED ISSUE #275: Post render pull-left, right

### PR DESCRIPTION
**Pull request by ue**
### What does this PR?
it just handle div class and styling
### Steps to reproduce
paste to editor these 
```
### FLOAT LEFT
<div class="pull-left">
contents here
</div>

### FLOAT RIGHT
<div class="pull-right"> 
contents here
</div>

### CENTRALIZE
<center>contents</center>

### JUSTIFY YOUR ARTICLE
<div class="text-justify">
contents here
</div> 

### RED COLOUR TETX
<div class="phishy"> contents here </div>
```
### Screenshots/Video
screen shot 2019-01-18 at 12 46 26

### CODE REVIEW

**Comment by ue** [comment]
@feruzm @mistikk Updated for gif and long tags

**Comment by ue** [comment]
can test using this post after new release https://steemit.com/table/@demo/jhj

**Comment by ue** [comment]
fixed please test @mistikk

**Comment by mistikk** [comment]
image
float left and gif not working on android @ue

**Pull request merged**
