### PR TITLE
Fixed sc login issue

### PR DESCRIPTION
**Pull request by mistikk**

### CODE REVIEW

**Comment by feruzm** [comment]
what issue does it solve? I thought all sc issues are gone, because nobody reported any more bugs unless this is fix for old bug report

**Comment by mistikk** [comment]
it is about authority issue. If login with steemconnect as 2, 3.. account (without first account) it throws authoriy error

**Comment by feruzm** [comment]
oh you mean if first account logout/removed then all other accounts 2,3 won't work?!

**Comment by feruzm** [comment]
If this is the case, yes we need to merge it after testing, I am sure Ugur will do some tests and I will check on device after testflight version.

**Comment by mistikk** [comment]
@feruzm when login with sc as first account, you can not see this issue. when you add a new account with sc login, you will see this error

**Pull request merged**
